# Generated by Django 3.2.13 on 2022-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='g_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
