# Generated by Django 3.2.13 on 2022-11-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='Likes',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='likeordislike',
        ),
    ]
