# Generated by Django 3.2.13 on 2022-11-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='re_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
