# Generated by Django 3.2.13 on 2022-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='joindate',
            field=models.DateField(auto_now=True),
        ),
    ]
