# Generated by Django 3.2.13 on 2022-11-10 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='joined_user',
            field=models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
