# Generated by Django 3.2.13 on 2022-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
