# Generated by Django 3.2.13 on 2022-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
