# Generated by Django 3.2.13 on 2022-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_study_joined_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
