# Generated by Django 3.2.13 on 2022-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_accepted_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='joindate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
