# Generated by Django 3.2.13 on 2022-11-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221114_1025'),
        ('reviews', '0002_auto_20221114_1131'),
    ]

    operations = [
    ]
