# Generated by Django 3.2.13 on 2022-11-11 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='joined_user',
        ),
        migrations.AlterField(
            model_name='study',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='study',
            name='limits',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
